DROP FUNCTION IF EXISTS modifyV1(eqID VARCHAR, val1 INTEGER);

CREATE OR REPLACE FUNCTION modifyV1(eqID VARCHAR, val1 INTEGER) RETURNS BOOLEAN AS
$$
BEGIN
	UPDATE equipamento set v1 = val1 where eID = eqID;
	RETURN TRUE;
END;
$$
LANGUAGE 'plpgsql';