DROP FUNCTION IF EXISTS modifyV2(eqID VARCHAR, val2 INTEGER);

CREATE OR REPLACE FUNCTION modifyV2(eqID VARCHAR, val2 INTEGER) RETURNS BOOLEAN AS
$$
BEGIN
	UPDATE equipamento set v2 = val2 where eID = eqID;
	RETURN TRUE;
END;
$$
LANGUAGE 'plpgsql';